import type { Field } from 'payload'

export const iconTextBlockFields: Field[] = [
  {
    name: 'icon',
    type: 'select',
    required: true,
    defaultValue: 'Heart',
    options: [
      { label: 'Heart', value: 'Heart' },
      { label: 'Clock', value: 'Clock' },
      { label: 'Check', value: 'Check' },
      { label: 'Star', value: 'Star' },
      { label: 'User', value: 'User' },
      { label: 'Mail', value: 'Mail' },
      { label: 'Phone', value: 'Phone' },
      { label: 'MapPin', value: 'MapPin' },
      { label: 'Calendar', value: 'Calendar' },
      { label: 'Shield', value: 'Shield' },
      { label: 'Zap', value: 'Zap' },
      { label: 'Activity', value: 'Activity' },
      { label: 'Scan', value: 'Scan' },
      { label: 'Stethoscope', value: 'Stethoscope' },
      { label: 'Settings', value: 'Settings' },
      { label: 'Info', value: 'Info' },
      { label: 'AlertCircle', value: 'AlertCircle' },
      { label: 'CheckCircle', value: 'CheckCircle' },
      { label: 'XCircle', value: 'XCircle' },
      { label: 'Plus', value: 'Plus' },
      { label: 'Minus', value: 'Minus' },
      { label: 'ArrowRight', value: 'ArrowRight' },
      { label: 'ArrowLeft', value: 'ArrowLeft' },
      { label: 'ArrowUp', value: 'ArrowUp' },
      { label: 'ArrowDown', value: 'ArrowDown' },
      { label: 'ExternalLink', value: 'ExternalLink' },
      { label: 'Download', value: 'Download' },
      { label: 'Upload', value: 'Upload' },
      { label: 'Search', value: 'Search' },
      { label: 'Filter', value: 'Filter' },
      { label: 'Menu', value: 'Menu' },
      { label: 'X', value: 'X' },
      { label: 'Eye', value: 'Eye' },
      { label: 'EyeOff', value: 'EyeOff' },
      { label: 'Lock', value: 'Lock' },
      { label: 'Unlock', value: 'Unlock' },
      { label: 'Key', value: 'Key' },
      { label: 'Home', value: 'Home' },
      { label: 'Building', value: 'Building' },
      { label: 'Globe', value: 'Globe' },
      { label: 'Wifi', value: 'Wifi' },
      { label: 'Bluetooth', value: 'Bluetooth' },
      { label: 'Battery', value: 'Battery' },
      { label: 'Volume2', value: 'Volume2' },
      { label: 'VolumeX', value: 'VolumeX' },
      { label: 'Play', value: 'Play' },
      { label: 'Pause', value: 'Pause' },
      { label: 'Stop', value: 'Stop' },
      { label: 'SkipBack', value: 'SkipBack' },
      { label: 'SkipForward', value: 'SkipForward' },
      { label: 'Repeat', value: 'Repeat' },
      { label: 'Shuffle', value: 'Shuffle' },
      { label: 'Sun', value: 'Sun' },
      { label: 'Moon', value: 'Moon' },
      { label: 'Cloud', value: 'Cloud' },
      { label: 'CloudRain', value: 'CloudRain' },
      { label: 'CloudSnow', value: 'CloudSnow' },
      { label: 'Wind', value: 'Wind' },
      { label: 'Thermometer', value: 'Thermometer' },
      { label: 'Droplets', value: 'Droplets' },
      { label: 'Umbrella', value: 'Umbrella' },
      { label: 'Sunrise', value: 'Sunrise' },
      { label: 'Sunset', value: 'Sunset' },
      { label: 'HelpCircle', value: 'HelpCircle' },
    ],
    admin: {
      description: 'Select an icon from the Lucide React icon library',
    },
  },
  {
    name: 'text',
    type: 'text',
    required: true,
    admin: {
      description: 'Text to display next to the icon',
    },
  },
  {
    name: 'iconPosition',
    type: 'select',
    defaultValue: 'left',
    options: [
      { label: 'Left', value: 'left' },
      { label: 'Right', value: 'right' },
      { label: 'Top', value: 'top' },
      { label: 'Bottom', value: 'bottom' },
    ],
    admin: {
      description: 'Position of the icon relative to the text',
    },
  },
  {
    name: 'iconSize',
    type: 'select',
    defaultValue: 'md',
    options: [
      { label: 'Small (16px)', value: 'sm' },
      { label: 'Medium (24px)', value: 'md' },
      { label: 'Large (32px)', value: 'lg' },
      { label: 'Extra Large (40px)', value: 'xl' },
    ],
    admin: {
      description: 'Size of the icon',
    },
  },
  {
    name: 'textSize',
    type: 'select',
    defaultValue: 'md',
    options: [
      { label: 'Small', value: 'sm' },
      { label: 'Medium', value: 'md' },
      { label: 'Large', value: 'lg' },
      { label: 'Extra Large', value: 'xl' },
    ],
    admin: {
      description: 'Size of the text',
    },
  },
  {
    name: 'textColor',
    type: 'select',
    defaultValue: 'default',
    options: [
      { label: 'Default (Dark Gray)', value: 'default' },
      { label: 'Primary (Dark Blue)', value: 'primary' },
      { label: 'Secondary (Pastille Green)', value: 'secondary' },
      { label: 'Accent (Yellow)', value: 'accent' },
    ],
    admin: {
      description: 'Color of the text',
    },
  },
  {
    name: 'iconColor',
    type: 'select',
    defaultValue: 'default',
    options: [
      { label: 'Default (Gray)', value: 'default' },
      { label: 'Primary (Dark Blue)', value: 'primary' },
      { label: 'Secondary (Pastille Green)', value: 'secondary' },
      { label: 'Accent (Yellow)', value: 'accent' },
    ],
    admin: {
      description: 'Color of the icon',
    },
  },
]
