declare module 'lucide-react' {
  import * as React from 'react'
  export const Facebook: React.FC<React.SVGProps<SVGSVGElement>>
  export const Twitter: React.FC<React.SVGProps<SVGSVGElement>>
  export const Instagram: React.FC<React.SVGProps<SVGSVGElement>>
  export const Linkedin: React.FC<React.SVGProps<SVGSVGElement>>
  export const X: React.FC<React.SVGProps<SVGSVGElement>>
  export const Menu: React.FC<React.SVGProps<SVGSVGElement>>
  export const ChevronLeft: React.FC<React.SVGProps<SVGSVGElement>>
  export const ChevronRight: React.FC<React.SVGProps<SVGSVGElement>>
  export const ChevronDown: React.FC<React.SVGProps<SVGSVGElement>>
  export const Search: React.FC<React.SVGProps<SVGSVGElement>>
  export const MoreHorizontal: React.FC<React.SVGProps<SVGSVGElement>>
  export const Share: React.FC<React.SVGProps<SVGSVGElement>>
  export const Copy: React.FC<React.SVGProps<SVGSVGElement>>
  export const Share2: React.FC<React.SVGProps<SVGSVGElement>>
  export const Check: React.FC<React.SVGProps<SVGSVGElement>>
  export const Calendar: React.FC<React.SVGProps<SVGSVGElement>>
  export const Settings: React.FC<React.SVGProps<SVGSVGElement>>
  export const Shield: React.FC<React.SVGProps<SVGSVGElement>>
  export const Zap: React.FC<React.SVGProps<SVGSVGElement>>
  export const Activity: React.FC<React.SVGProps<SVGSVGElement>>
  export const Heart: React.FC<React.SVGProps<SVGSVGElement>>
  export const Scan: React.FC<React.SVGProps<SVGSVGElement>>
  export const Stethoscope: React.FC<React.SVGProps<SVGSVGElement>>
  export const FileText: React.FC<React.SVGProps<SVGSVGElement>>
  export const PhoneCall: React.FC<React.SVGProps<SVGSVGElement>>
  export const Beaker: React.FC<React.SVGProps<SVGSVGElement>>
  export const ChevronUp: React.FC<React.SVGProps<SVGSVGElement>>
  export const ArrowRight: React.FC<React.SVGProps<SVGSVGElement>>
  export const SquareActivity: React.FC<React.SVGProps<SVGSVGElement>>
  export const Clock: React.FC<React.SVGProps<SVGSVGElement>>
  export const CheckCircle: React.FC<React.SVGProps<SVGSVGElement>>
  export const Users: React.FC<React.SVGProps<SVGSVGElement>>
  export const AlertTriangle: React.FC<React.SVGProps<SVGSVGElement>>
  export const Brain: React.FC<React.SVGProps<SVGSVGElement>>
  export const Moon: React.FC<React.SVGProps<SVGSVGElement>>
  export const Baby: React.FC<React.SVGProps<SVGSVGElement>>
  export const Phone: React.FC<React.SVGProps<SVGSVGElement>>
  export const TrendingUp: React.FC<React.SVGProps<SVGSVGElement>>
  export const HeartHandshake: React.FC<React.SVGProps<SVGSVGElement>>
  export const ClipboardList: React.FC<React.SVGProps<SVGSVGElement>>
  export const UserCheck: React.FC<React.SVGProps<SVGSVGElement>>
  export const List: React.FC<React.SVGProps<SVGSVGElement>>
  export const UserPlus: React.FC<React.SVGProps<SVGSVGElement>>
  export const BriefcaseMedical: React.FC<React.SVGProps<SVGSVGElement>>
  export const BarChart3: React.FC<React.SVGProps<SVGSVGElement>>
  export const RefreshCw: React.FC<React.SVGProps<SVGSVGElement>>
  export const Truck: React.FC<React.SVGProps<SVGSVGElement>>
  export const Monitor: React.FC<React.SVGProps<SVGSVGElement>>
  export const Home: React.FC<React.SVGProps<SVGSVGElement>>
  export const Video: React.FC<React.SVGProps<SVGSVGElement>>
  export const Waves: React.FC<React.SVGProps<SVGSVGElement>>
  export const Eye: React.FC<React.SVGProps<SVGSVGElement>>
  export const EyeOff: React.FC<React.SVGProps<SVGSVGElement>>
  export const Building: React.FC<React.SVGProps<SVGSVGElement>>
  export const Build: React.FC<React.SVGProps<SVGSVGElement>>
  export const Building2: React.FC<React.SVGProps<SVGSVGElement>>
  export const AlertCircle: React.FC<React.SVGProps<SVGSVGElement>>
  export const Loader2: React.FC<React.SVGProps<SVGSVGElement>>
}
