/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    blogs: Blog;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Controls access to content and admin features
   */
  role: 'viewer' | 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Upload images, documents, and other media files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility
   */
  alt: string;
  /**
   * Optional caption for the media
   */
  caption?: string | null;
  /**
   * Photo credit or attribution
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Create pages with flexible content blocks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Page title displayed in the browser tab and page header
   */
  title: string;
  /**
   * URL path for this page. Example: about, blog/my-post
   */
  slug?: string | null;
  /**
   * Content displayed within the Hero when Show Hero is enabled
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional background image for the Hero section when Show Hero is enabled
   */
  heroBackground?: (number | null) | Media;
  /**
   * If enabled, the hero is rendered using the Hero Content rich text.
   */
  showHero?: boolean | null;
  /**
   * Text color scheme for hero content
   */
  heroTextColor?: ('auto' | 'light' | 'dark') | null;
  /**
   * Add a gradient overlay for better text readability
   */
  heroGradientOverlay?: boolean | null;
  /**
   * Primary call-to-action button for the hero section
   */
  heroCTAButton?: {
    /**
     * Button text
     */
    label?: string | null;
    /**
     * Choose between internal page/blog or external URL
     */
    linkType?: ('internal' | 'external') | null;
    /**
     * Link to an internal page or blog post
     */
    internal?: {
      /**
       * Choose the page or blog to link to
       */
      relation?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'blogs';
            value: number | Blog;
          } | null);
    };
    /**
     * Link to an external website
     */
    external?: {
      /**
       * External URL (e.g., https://example.com)
       */
      href?: string | null;
    };
    /**
     * Button style variant
     */
    variant?: ('primary' | 'secondary') | null;
  };
  /**
   * Secondary call-to-action button (optional)
   */
  heroSecondaryCTA?: {
    /**
     * Button text
     */
    label?: string | null;
    /**
     * Choose between internal page/blog or external URL
     */
    linkType?: ('internal' | 'external') | null;
    /**
     * Link to an internal page or blog post
     */
    internal?: {
      /**
       * Choose the page or blog to link to
       */
      relation?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'blogs';
            value: number | Blog;
          } | null);
    };
    /**
     * Link to an external website
     */
    external?: {
      /**
       * External URL (e.g., https://example.com)
       */
      href?: string | null;
    };
  };
  /**
   * Choose the alignment for the hero CTA buttons
   */
  heroCTAAlignment?: ('left' | 'center' | 'right') | null;
  /**
   * Add flexible content blocks to build your page layout
   */
  blocks?:
    | (
        | {
            title?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            layout?: ('full' | 'split') | null;
            image?: (number | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentBlock';
          }
        | {
            columns?: number | null;
            cards: {
              image?: (number | null) | Media;
              title: string;
              text?: string | null;
              href?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardSection';
          }
        | {
            image: number | Media;
            imagePosition?: ('left' | 'right') | null;
            title: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaButton?: {
              label?: string | null;
              href?: string | null;
            };
            backgroundColor?: ('default' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            title: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            description?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaButton: {
              label: string;
              href: string;
            };
            align?: ('left' | 'center' | 'right') | null;
            variant?: ('default' | 'accent' | 'gradient') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
        | {
            title: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            ctaButton?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutUsSection';
          }
        | {
            title: string;
            layout?: ('grid' | 'carousel') | null;
            partners: {
              logo: number | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnersBlock';
          }
        | {
            title: string;
            partners: {
              name: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnersTextBlock';
          }
        | {
            title: string;
            subtitle?: string | null;
            description: string;
            /**
             * Enable search functionality for the table items
             */
            enableSearch?: boolean | null;
            searchPlaceholder?: string | null;
            items: {
              title: string;
              content: string;
              /**
               * Additional details that will be shown when expanded
               */
              details?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'expandableTable';
          }
        | {
            title: string;
            testimonialType?: ('custom' | 'doctify') | null;
            testimonials?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  id?: string | null;
                }[]
              | null;
            doctifyConfig?: {
              widgetId: string;
              tenant: string;
              language: string;
              profileType: string;
              layoutType: string;
              slugs: string;
              background: string;
              itemBackground: string;
              itemFrame?: boolean | null;
            };
            autoplayInterval?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title: string;
            subtitle?: string | null;
            members: {
              image: number | Media;
              name: string;
              description: string;
              linkedin?: string | null;
              imagePosition?: ('left' | 'right') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamCards';
          }
        | {
            posts?:
              | {
                  image?: (number | null) | Media;
                  title: string;
                  excerpt?: string | null;
                  linkType?: ('internal' | 'external') | null;
                  href?: string | null;
                  post?: {
                    relationTo: 'blogs';
                    value: number | Blog;
                  } | null;
                  date?: string | null;
                  author?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogPostCards';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Disable scroll observer for instant visibility
             */
            disableObserver?: boolean | null;
            /**
             * Make entire card clickable instead of just the link
             */
            clickableCard?: boolean | null;
            posts?:
              | {
                  image?: (number | null) | Media;
                  category?: string | null;
                  author?: string | null;
                  date?: string | null;
                  readTime?: string | null;
                  title: string;
                  excerpt?: string | null;
                  linkType?: ('internal' | 'external') | null;
                  href?: string | null;
                  post?: {
                    relationTo: 'blogs';
                    value: number | Blog;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'scrollPostCards';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            cards: {
              title: string;
              icon?:
                | (
                    | 'Heart'
                    | 'Activity'
                    | 'Users'
                    | 'Shield'
                    | 'Star'
                    | 'CheckCircle'
                    | 'Lightbulb'
                    | 'Target'
                    | 'TrendingUp'
                    | 'Award'
                    | 'Zap'
                    | 'Leaf'
                    | 'Globe'
                    | 'Clock'
                    | 'MapPin'
                    | 'Phone'
                    | 'Mail'
                    | 'MessageCircle'
                    | 'Calendar'
                    | 'FileText'
                  )
                | null;
              content: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'scrollableCards';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            items?:
              | {
                  image: number | Media;
                  title: string;
                  description?: string | null;
                  buttonText?: string | null;
                  linkType?: ('internal' | 'external') | null;
                  internal?: {
                    relation?:
                      | ({
                          relationTo: 'pages';
                          value: number | Page;
                        } | null)
                      | ({
                          relationTo: 'blogs';
                          value: number | Blog;
                        } | null);
                  };
                  external?: {
                    href?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            slidesToShow?: number | null;
            autoplay?: boolean | null;
            autoplayInterval?: number | null;
            showArrows?: boolean | null;
            showDots?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carousel';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            items: {
              image: number | Media;
              title: string;
              description: string;
              links?:
                | {
                    text: string;
                    variant?: ('primary' | 'secondary') | null;
                    linkType?: ('internal' | 'external') | null;
                    internal?: {
                      relation:
                        | {
                            relationTo: 'pages';
                            value: number | Page;
                          }
                        | {
                            relationTo: 'blogs';
                            value: number | Blog;
                          };
                    };
                    external?: {
                      href: string;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoCardBlock';
          }
        | {
            title: string;
            subtitle?: string | null;
            buttonText: string;
            linkType?: ('internal' | 'external') | null;
            internal?: {
              relation?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'blogs';
                    value: number | Blog;
                  } | null);
            };
            external?: {
              href?: string | null;
            };
            openInNewTab?: boolean | null;
            backgroundImage: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fullWidthBanner';
          }
        | {
            title: string;
            subtitle: string;
            buttonText: string;
            buttonHref: string;
            backgroundImage: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'parallaxHero';
          }
        | {
            title: string;
            subtitle?: string | null;
            image: number | Media;
            enableBackground?: boolean | null;
            imagePosition?: ('left' | 'right') | null;
            linkType?: ('internal' | 'external') | null;
            internal?: {
              relation?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'blogs';
                    value: number | Blog;
                  } | null);
            };
            external?: {
              href?: string | null;
            };
            cta?: {
              text?: string | null;
              variant?: ('primary' | 'secondary' | 'outline' | 'ghost') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'singleCard';
          }
        | {
            /**
             * Main heading for the services banner section
             */
            title?: string | null;
            /**
             * Small subtitle text above the main title
             */
            subtitle?: string | null;
            /**
             * Background image for the section (optional)
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Background color for the section
             */
            backgroundColor?: ('slate-800' | 'ds-dark-blue' | 'ds-pastille-green' | 'gray-900' | 'blue-900') | null;
            /**
             * Text color for the section
             */
            textColor?: ('white' | 'gray-100' | 'ds-dark-blue') | null;
            /**
             * Service option cards (1-3 options)
             */
            options: {
              /**
               * Icon for this service option
               */
              icon?: ('calendar' | 'settings' | 'shield') | null;
              /**
               * Title for this service option
               */
              title: string;
              /**
               * Description text for this service option
               */
              description: string;
              /**
               * Text for the call-to-action button
               */
              buttonText?: string | null;
              /**
               * Link configuration for this service option
               */
              link?: {
                linkType?: ('internal' | 'external') | null;
                internal?: {
                  relation:
                    | {
                        relationTo: 'pages';
                        value: number | Page;
                      }
                    | {
                        relationTo: 'blogs';
                        value: number | Blog;
                      };
                };
                external?: {
                  /**
                   * External URL (e.g., https://example.com)
                   */
                  href: string;
                };
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesBannerBlock';
          }
        | {
            /**
             * Main heading for the medical services grid section
             */
            title?: string | null;
            /**
             * Small subtitle text above the main title
             */
            subtitle?: string | null;
            /**
             * Background color for the section
             */
            backgroundColor?: ('gray-50' | 'white' | 'blue-50' | 'green-50') | null;
            /**
             * Medical service cards (1-8 services)
             */
            services: {
              /**
               * Icon for this medical service
               */
              icon?:
                | ('scan' | 'activity' | 'zap' | 'heart' | 'stethoscope' | 'check' | 'calendar' | 'settings' | 'shield')
                | null;
              /**
               * Name of the medical service (e.g., MRI, ULTRASOUND)
               */
              name: string;
              /**
               * Show "Available for self-pay" badge
               */
              available?: boolean | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'medicalServicesGrid';
          }
        | {
            /**
             * Optional section title displayed above the content blocks
             */
            title?: string | null;
            /**
             * Default: Each block uses its individual image position. Alternating: Automatically alternates image position for a zigzag pattern.
             */
            layout: 'default' | 'alternating';
            /**
             * Array of content blocks to display
             */
            contentBlocks: {
              /**
               * Title for this content block
               */
              title: string;
              /**
               * Description text for this content block
               */
              description: string;
              /**
               * Image for this content block
               */
              image: number | Media;
              /**
               * Position of the image relative to the text content
               */
              imagePosition: 'left' | 'right';
              /**
               * Text for the call-to-action button (optional)
               */
              buttonText?: string | null;
              /**
               * Choose whether to link to an internal page or external URL
               */
              linkType?: ('internal' | 'external') | null;
              internal?: {
                /**
                 * Type of content to link to
                 */
                relationTo: 'pages' | 'blogs';
                /**
                 * Slug of the page or blog to link to
                 */
                value: string;
              };
              external?: {
                /**
                 * External URL (e.g., https://example.com)
                 */
                href: string;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentBlockArray';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * Hide the page header
   */
  hideHeader?: boolean | null;
  /**
   * Hide the page footer
   */
  hideFooter?: boolean | null;
  /**
   * Use full width layout instead of container
   */
  fullWidth?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  image?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: string | null;
  category?: string | null;
  readTime?: string | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'pages';
        value: number | Page;
      }
    | {
        relationTo: 'blogs';
        value: number | Blog;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  heroBackground?: T;
  showHero?: T;
  heroTextColor?: T;
  heroGradientOverlay?: T;
  heroCTAButton?:
    | T
    | {
        label?: T;
        linkType?: T;
        internal?:
          | T
          | {
              relation?: T;
            };
        external?:
          | T
          | {
              href?: T;
            };
        variant?: T;
      };
  heroSecondaryCTA?:
    | T
    | {
        label?: T;
        linkType?: T;
        internal?:
          | T
          | {
              relation?: T;
            };
        external?:
          | T
          | {
              href?: T;
            };
      };
  heroCTAAlignment?: T;
  blocks?:
    | T
    | {
        contentBlock?:
          | T
          | {
              title?: T;
              content?: T;
              layout?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        cardSection?:
          | T
          | {
              columns?: T;
              cards?:
                | T
                | {
                    image?: T;
                    title?: T;
                    text?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              image?: T;
              imagePosition?: T;
              title?: T;
              content?: T;
              ctaButton?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              title?: T;
              description?: T;
              ctaButton?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              align?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        aboutUsSection?:
          | T
          | {
              title?: T;
              content?: T;
              image?: T;
              ctaButton?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partnersBlock?:
          | T
          | {
              title?: T;
              layout?: T;
              partners?:
                | T
                | {
                    logo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partnersTextBlock?:
          | T
          | {
              title?: T;
              partners?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        expandableTable?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              enableSearch?: T;
              searchPlaceholder?: T;
              items?:
                | T
                | {
                    title?: T;
                    content?: T;
                    details?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              testimonialType?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    id?: T;
                  };
              doctifyConfig?:
                | T
                | {
                    widgetId?: T;
                    tenant?: T;
                    language?: T;
                    profileType?: T;
                    layoutType?: T;
                    slugs?: T;
                    background?: T;
                    itemBackground?: T;
                    itemFrame?: T;
                  };
              autoplayInterval?: T;
              id?: T;
              blockName?: T;
            };
        teamCards?:
          | T
          | {
              title?: T;
              subtitle?: T;
              members?:
                | T
                | {
                    image?: T;
                    name?: T;
                    description?: T;
                    linkedin?: T;
                    imagePosition?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        blogPostCards?:
          | T
          | {
              posts?:
                | T
                | {
                    image?: T;
                    title?: T;
                    excerpt?: T;
                    linkType?: T;
                    href?: T;
                    post?: T;
                    date?: T;
                    author?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        scrollPostCards?:
          | T
          | {
              title?: T;
              subtitle?: T;
              disableObserver?: T;
              clickableCard?: T;
              posts?:
                | T
                | {
                    image?: T;
                    category?: T;
                    author?: T;
                    date?: T;
                    readTime?: T;
                    title?: T;
                    excerpt?: T;
                    linkType?: T;
                    href?: T;
                    post?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        scrollableCards?:
          | T
          | {
              title?: T;
              subtitle?: T;
              cards?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        carousel?:
          | T
          | {
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    buttonText?: T;
                    linkType?: T;
                    internal?:
                      | T
                      | {
                          relation?: T;
                        };
                    external?:
                      | T
                      | {
                          href?: T;
                        };
                    id?: T;
                  };
              slidesToShow?: T;
              autoplay?: T;
              autoplayInterval?: T;
              showArrows?: T;
              showDots?: T;
              id?: T;
              blockName?: T;
            };
        twoCardBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    links?:
                      | T
                      | {
                          text?: T;
                          variant?: T;
                          linkType?: T;
                          internal?:
                            | T
                            | {
                                relation?: T;
                              };
                          external?:
                            | T
                            | {
                                href?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fullWidthBanner?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonText?: T;
              linkType?: T;
              internal?:
                | T
                | {
                    relation?: T;
                  };
              external?:
                | T
                | {
                    href?: T;
                  };
              openInNewTab?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        parallaxHero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonText?: T;
              buttonHref?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        singleCard?:
          | T
          | {
              title?: T;
              subtitle?: T;
              image?: T;
              enableBackground?: T;
              imagePosition?: T;
              linkType?: T;
              internal?:
                | T
                | {
                    relation?: T;
                  };
              external?:
                | T
                | {
                    href?: T;
                  };
              cta?:
                | T
                | {
                    text?: T;
                    variant?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesBannerBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              backgroundImage?: T;
              backgroundColor?: T;
              textColor?: T;
              options?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    buttonText?: T;
                    link?:
                      | T
                      | {
                          linkType?: T;
                          internal?:
                            | T
                            | {
                                relation?: T;
                              };
                          external?:
                            | T
                            | {
                                href?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        medicalServicesGrid?:
          | T
          | {
              title?: T;
              subtitle?: T;
              backgroundColor?: T;
              services?:
                | T
                | {
                    icon?: T;
                    name?: T;
                    available?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contentBlockArray?:
          | T
          | {
              title?: T;
              layout?: T;
              contentBlocks?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    imagePosition?: T;
                    buttonText?: T;
                    linkType?: T;
                    internal?:
                      | T
                      | {
                          relationTo?: T;
                          value?: T;
                        };
                    external?:
                      | T
                      | {
                          href?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  hideHeader?: T;
  hideFooter?: T;
  fullWidth?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  image?: T;
  content?: T;
  author?: T;
  category?: T;
  readTime?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  ctaButton?: {
    label?: string | null;
    linkType?: ('internal' | 'external') | null;
    page?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'blogs';
          value: number | Blog;
        } | null);
    href?: string | null;
  };
  enableBanter?: boolean | null;
  /**
   * Optional description text shown above the site header
   */
  headerDescription?: string | null;
  navigation?:
    | {
        label: string;
        hasMegaMenu?: boolean | null;
        linkType?: ('internal' | 'external') | null;
        page?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'blogs';
              value: number | Blog;
            } | null);
        href?: string | null;
        megaMenu?: {
          categories?:
            | {
                title: string;
                items?:
                  | {
                      label: string;
                      linkType?: ('internal' | 'external') | null;
                      page?:
                        | ({
                            relationTo: 'pages';
                            value: number | Page;
                          } | null)
                        | ({
                            relationTo: 'blogs';
                            value: number | Blog;
                          } | null);
                      href?: string | null;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          featured?:
            | {
                label: string;
                linkType?: ('internal' | 'external') | null;
                page?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'blogs';
                      value: number | Blog;
                    } | null);
                href?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  about?: string | null;
  navigationLinks?:
    | {
        label: string;
        linkType?: ('internal' | 'external') | null;
        page?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'blogs';
              value: number | Blog;
            } | null);
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        linkType?: ('internal' | 'external') | null;
        page?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'blogs';
              value: number | Blog;
            } | null);
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  socialLinks?:
    | {
        platform?: ('facebook' | 'twitter' | 'linkedin' | 'x') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  ctaButton?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        href?: T;
      };
  enableBanter?: T;
  headerDescription?: T;
  navigation?:
    | T
    | {
        label?: T;
        hasMegaMenu?: T;
        linkType?: T;
        page?: T;
        href?: T;
        megaMenu?:
          | T
          | {
              categories?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          label?: T;
                          linkType?: T;
                          page?: T;
                          href?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              featured?:
                | T
                | {
                    label?: T;
                    linkType?: T;
                    page?: T;
                    href?: T;
                    id?: T;
                  };
            };
        external?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  about?: T;
  navigationLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        href?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        href?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}